stages:
  - mirror
  - deploy


mirror:
  stage: mirror
  only:
    refs:
      - /^(main.*)$/
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/mirror.sh
  tags:
    - amirplatform

amir-gateway:
  stage: deploy
  script:
    - chmod +x ./install.sh
    - ./install.sh -e gateway
  only:
    refs:
      - /^(main.*)$/
    changes:
      - env/gateway.yml
      - roles/sudo/**/*
      - roles/common/**/*
      - roles/ssh/**/*
      - roles/fail2ban/**/*
      - roles/kinsing/**/*
      - roles/firewall/**/*
      - roles/docker/**/*
      - roles/gw-letsencrypt/**/*
      - roles/backup-logs/**/*
      - roles/gw-nginx/**/*
      - roles/gitlab-runner/**/*
      - install.sh
      - playbook-gateway.yml
  tags:
    - amirplatform
