---
ssh_key_user: almalinux
ssh_key_group: almalinux

ssh_public_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSAEcxeA7dEd040faaL2F+YZZwfjAKZt8EXBkG8tn7Ov9WBVBsGut3HbRNBk1rBdtTuybAPdjbkY374cYOPoOXZKHIpt3chco1rtqB5pFt+8U3i70rhwuUmmYj2yzkMkEnV3XDB9JSE2M7XtIn95bZSaobV/JOGfmx8ghoY+zNKngxanMuwmxbXScSpO1FhzjqklZAslr0ETQNxGNnTvsBKqtsmsxIyVtxr6aZQnGvGSgZ2DJNHP58QjVZT6ei0SMk06uJ4PhvHO9v1PGTMnyAvU2kXcVIJyw8M/8dgyhianM9UJf7Xg0IS4O2W4HZF7zEXZoXhEW0PzsVu/jmWp52D1blLwQivhHLDW0rFriIteOpXIshuxmyoUQ2VQNwl1memlXOzXZoORi7iNoWHSZgc1CrevYChfnlxchO7ohNmklksfeHQJfx0uiTs7Eq55/1OpCWFtVOa2mjKhh5pl48h9PB+menCCApWnGHrdRvh6uU/8dSq51abummgFZObeM= ghediraamir@Ghediras-MacBook-Pro.local