galaxy_info:
  role_name: docker-cleanup
  author: Amir Ghedira
  description: create cron to clean up machine from useless docker images
  company: Amir Platform

  min_ansible_version: 2.2

  platforms:
    - name: CentOS
