---
- name: change root password
  become: yes
  user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"


- name: Disable SELinux
  become: yes
  command: "setenforce 0"
  ignore_errors: yes

- name: Deploy user is created
  become: yes
  user:
    name: "{{ deploy_user }}"
